# Generated by Django 3.1.2 on 2020-10-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('telnum', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('agree', models.BooleanField()),
                ('contactType', models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('tel', 'Tel')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
