# Generated by Django 3.1.2 on 2020-10-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('designation', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=50)),
                ('featured', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
